# Generated by Django 5.0.2 on 2024-03-29 21:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafewebsite', '0002_remove_menu_image_menu_image1_menu_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image3',
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafewebsite.menu')),
            ],
        ),
    ]
