# Generated by Django 5.0.2 on 2024-03-29 22:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafewebsite', '0004_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
