# Generated by Django 5.0.2 on 2024-03-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafewebsite', '0005_menu_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image1',
        ),
    ]
